name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📂 Show current working directory
        run: pwd

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install
        working-directory: ./

      - name: 🔍 Check package.json exists
        run: |
          ls -la
          cat package.json
        working-directory: ./

      - name: 🧪 Show available npm scripts
        run: npm run
        working-directory: ./

      - name: 🧪 Run tests
        run: npm run test:ci
        working-directory: ./

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: 🚀 Deploy based on branch
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "🚀 Deploying to DEVELOPMENT environment"
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "🚀 Deploying to PRODUCTION environment"
          else
            echo "❌ Unsupported branch"
            exit 1
          fi
