name: My first workflow

on: push

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Display workplace
        run: pwd
      - run: echo "second step"
      - run: ls
