# test
name: PizzaCI - Express

on:
  workflow_dispatch:
    inputs:
      nom_client:
        description: "Nom du client"
        required: true
      pizzas:
        description: |
          Liste des pizzas au format JSON. Attention aux points importants:
          - Utilisez des guillemets doubles
          - Entourez la liste avec []
          Exemple: ["margherita","reine","calzone"]
        required: true

jobs:
  reception-commande:
    name: Réception de la commande
    runs-on: ubuntu-latest
    outputs:
      pizzas: ${{ steps.export.outputs.pizzas }}
    steps:
      - name: Accueil client
        run: echo "Bienvenue ${{ github.event.inputs.nom_client }} chez PizzaCI - Express!"

      - name: Confirmation commande
        id: export
        run: |
          echo "Client: ${{ github.event.inputs.nom_client }}"
          echo "Commandes: ${{ github.event.inputs.pizzas }}"
          echo "pizzas=${{ github.event.inputs.pizzas }}" >> $GITHUB_OUTPUT

  cuisine:
    name: Cuisine
    runs-on: ubuntu-latest
    needs: reception-commande
    strategy:
      matrix:
        pizza: ${{ fromJSON(needs.reception-commande.outputs.pizzas) }}
        taille: ["L", "XL"]
        include:
          - pizza: "tiramisu"
            taille: "M"

    steps:
      - name: Préparation
        run: echo "Préparation de la pizza '${{ matrix.pizza }}' en taille '${{ matrix.taille }}'"

  livraison:
    name: Livraison
    runs-on: ubuntu-latest
    needs: cuisine
    concurrency:
      group: livraison
      cancel-in-progress: true
    steps:
      - name: Livraison
        run: |
          echo "Préparation de la livraison pour ${{ github.event.inputs.nom_client }}"
          echo "Les pizzas à livrer sont : ${{ github.event.inputs.pizzas }}"

  reclamation:
    name: Gestion des réclamations
    runs-on: ubuntu-latest
    needs: livraison
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Créer une issue si problème
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --title "Réclamation client: ${{ github.event.inputs.nom_client }}" \
            --body "Une réclamation a été enregistrée suite à la livraison des pizzas: ${{ github.event.inputs.pizzas }}."
